config/routes.rb
Rails.application.routes.draw do
  get   'index', to: 'pages#index'  
  get   'detail', to: 'pages#detail'    
  get   'nearby', to: 'pages#nearby'  
  post  'keyword', to: 'pages#keyword'      
  get   'keyword', to: 'pages#keyword'    
  get   'statistics', to:'pages#statistics'
  root :to => 'pages#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  require 'net/http'
  require 'json'

  def index
  end

  def keyword
    @split_string = params[:str].split(",").map {|s| s.strip}.first(10)
    @first_string = @split_string.first
    if params[:token]
      wow_get_next_page_url = ENV["api_get_next_page_keyword_url"] + "?token=#{params[:token]}"
      encoded_url = URI.encode(wow_get_next_page_url)
      uri = URI.parse(encoded_url)
      @places = JSON.parse(Net::HTTP.get(uri))            
    else
      wow_search_keyword_url = ENV["api_search_by_keyword_url"] + "?str=#{@first_string}&opt=#{params[:opt]}"
      encoded_url = URI.encode(wow_search_keyword_url)
      uri = URI.parse(encoded_url)
      @places = JSON.parse(Net::HTTP.get(uri))      
    end      
  end

  def nearby
    if params[:token]
      wow_get_next_page_url = ENV["api_get_next_page_pid_url"] + "?pid=#{params[:pid]}&token=#{params[:token]}"
      encoded_url = URI.encode(wow_get_next_page_url)
      uri = URI.parse(encoded_url)
      @places = JSON.parse(Net::HTTP.get(uri)) 
    else
      if params[:new_str].nil?
        wow_detail_url = ENV["api_get_detail_url"] + "?pid=#{params[:pid]}"
        encoded_url = URI.encode(wow_detail_url)
        uri = URI.parse(encoded_url)
        @place = JSON.parse(Net::HTTP.get(uri))   
        params[:new_str] = @place["name"]
      end      
      wow_search_pid_url = ENV["api_search_by_pid_url"] + "?pid=#{params[:pid]}&opt=#{params[:new_opt]}"
      encoded_url = URI.encode(wow_search_pid_url)
      uri = URI.parse(encoded_url)
      @places = JSON.parse(Net::HTTP.get(uri))      
    end
  end

  def detail
    wow_detail_url = ENV["api_get_detail_url"] + "?pid=#{params[:pid]}"
    encoded_url = URI.encode(wow_detail_url)
    uri = URI.parse(encoded_url)
    @place = JSON.parse(Net::HTTP.get(uri))      
  end

  def statistics
    get_statistics
  end

  private
  def get_statistics
    wow_api_statistics_url = ENV["api_get_statistics_url"]
    encoded_url = URI.encode(wow_api_statistics_url)
    uri = URI.parse(encoded_url)
    @statistics = JSON.parse(Net::HTTP.get(uri))    

    @statistics["keyword_count"].sort_by! { |k| -k["count"] }    
    @statistics["pid_count"].sort_by! { |k| -k["count"] }    
    @statistics["detail_count"].sort_by! { |k| -k["count"] }    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" style="margin: 0; padding: 30px; background-color: #eeeeee; height: 110px; border: 0;">
  <div class="container-fluid" >
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "幫旅", root_path, class: "navbar-brand", style:"font-size: 1.8em;" %>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse"> 
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "統計資料", statistics_path, style:"font-size: 1.3em;" %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>幫旅</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyB0UED0ms1Q349SuuKxosnRgab8JNQJwys&signed_in=true&libraries=places" %>  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "common/navbar" %>
<%= yield %>

</body>
</html>

app/views/pages/_history.html.erb
<h4>v1.00:&nbsp&nbsp&nbspInitial Release</h4>
<h4>v1.01:&nbsp『PID搜尋地點』新增Distnace/Duration欄位 (使用Google MAP Distance Matrix API)</h4>
<h4>v1.02:&nbsp&nbsp&nbsp新增搜尋景點顯示地圖 (使用Google MAP Javascript API)</h4>
<h4>v1.03:&nbsp『關鍵字搜尋地點』『PID搜尋地點』新增加 next_page_token</h4>
<h4>v1.04:&nbsp&nbsp&nbspModify API URL path (add version control)</h4>
<h4>v1.05:&nbsp&nbsp&nbspSeperate API backend and View frontend to two sites</h4>
<h4>v1.06:&nbsp&nbsp&nbsp新增『搜尋下一頁』 </h4>
<h4>v1.07:&nbsp&nbsp&nbsp新增『座標搜尋地點』 </h4>
<h4>v1.08:&nbsp&nbsp&nbsp新增搜尋字串統計資料 </h4>
<h4>v1.09:&nbsp&nbsp&nbsp新增用逗點隔開可搜尋多個地點 </h4>
<h4>v1.10:&nbsp&nbsp&nbsp新增tripadvisor來源 </h4>
<h4>v1.11:&nbsp&nbsp&nbsp新增Google Translate </h4>

app/views/pages/_place_list.html.erb
<br>
<% @places["results"].each do |r| %> 
  <% if r["photo_ref"] %>
    <% photo_url = "https://maps.googleapis.com/maps/api/place/photo?maxwidth=400&photoreference=" +
                   r["photo_ref"] + 
                   "&key=#{ENV["google_api_key"]}" %>      
  <% end %>

  <div class="media">
    <div class="media-left" style="padding-right: 80px;">
      <%= link_to "#" do %>
        <div style="width: 100px; height: 100px;">
          <% if r["photo_ref"] %>
            <%= image_tag(photo_url, class: 'media-object', style:"width: 85%; height: 85%; border-radius: 50%;") %>
          <% else %>
            <%= image_tag("black.jpg", class: 'media-object', style:"width: 85%; height: 85%; border-radius: 50%;") %>
          <% end %>
        </div>

      <% end %>
    </div>
    <% nearby_margin_top = nearby ? "0px" : "7px" %> 
    <div class="media-body" style="padding-top: 0px;">
      <h3 class="media-heading" style="font-size: 20px;  margin-bottom: 8px; margin-top: <%= nearby_margin_top %>;">
        <% link_path = detail_path(str: params[:str],
                                   opt: params[:opt],
                                   pid: r["pid"]) %>

        <%= link_to r["name"] + " (#{r["eng_name"]})" + " (#{r["ori_name"]})", link_path %> 
        
      </h3>
      <% if r["rating"] %>
        <h4 style="font-size: 14px; margin: 0px;">
          <b>景點評分：</b><span style="color: #e7711b;"><%= r["rating"] %>&nbsp</span>
          <% r["rating"].floor.times do %>
            <span class="glyphicon glyphicon-star" style="top: 3px; color: #e7711b;"></span>
          <% end %>
          <% (5-r["rating"].floor).times do %>
            <span class="glyphicon glyphicon-star-empty" style="top: 3px; color: #e7711b;"></span>
          <% end %>
        </h4>
      <% end %>
      <h4 style="font-size: 14px; margin: 0px;"><b>景點分類：</b><%= r["types"] %></h4>
      <% if nearby %>
        <h4 style="font-size: 14px; margin: 0px;"><b>景點距離：</b><%= r["distance"] %>, 步行 <%= r["duration"] %>鐘</h4>
      <% end %>
    </div>            
  </div>            
<% end %>  

app/views/pages/_tripadvisor_list.html.erb
<br><br>
<% @places["tripadvisor"].each_with_index do |t, i| %> 
  <div class="media">
    <div class="media-body" style="padding-top: 0px;">
      <h3 class="media-heading" style="font-size: 20px;  margin-bottom: 8px; margin-top: 7px;">
        排名第<%= t["order"] %>：<%= link_to t["title"], t["link"] %> 
        <% if t["rate"] %>
          ( 評分 <span style="color: #e7711b;"><%= t["rate"] %> </span> )
        <% end %>
        <% if t["review"] %>
          ( <span style="color: #e7711b;"><%= t["review"] %></span> 則評論 )
        <% end %>   
      </h3>
    </div>            
  </div>       
<% end %>  

app/views/pages/detail.html.erb
<br><br> 
<div class="container col-xs-8" style="left:16.7%">
  <div class="well" id="detail-well">
    <h1>
      <%= @place["name"] + " (#{@place["eng_name"]})" + " (#{@place["ori_name"]})" %>
      <% if params[:str] && params[:opt] %>   
        <%= link_to "返回", keyword_path(str: params[:str], opt: params[:opt]), class:"pull-right", style:"font-size: 0.7em" %>
      <% else %>
        <%= link_to "返回", root_path, class:"pull-right", style:"font-size: 0.7em" %>
      <% end %>      
      <br>
      <span style="color: #e7711b; font-size: 0.6em; margin-left: 5px; position: relative; top:-3px;">
        <% if @place["rating"] %>
          <%= @place["rating"] %>&nbsp
          <% @place["rating"].floor.times do %>
            <span class="glyphicon glyphicon-star" style="top: 3px"></span>
          <% end %>
          <% (5-@place["rating"].floor).times do %>
            <span class="glyphicon glyphicon-star-empty" style="top: 3px"></span>
          <% end %>
          &nbsp&nbsp&nbsp&nbsp
        <% end %>   
      </span>       
    </h1>
    <h1 style="margin-top: 0">
      <span id="detail-label">
        <span class="label label-default" style="margin-left:0">
          <%= link_to "附近景點", nearby_path(pid: @place["pid"], 
                                             str: params[:str], 
                                             opt: params[:opt], 
                                             new_str: @place["name"], 
                                             new_opt: "景點"), 
                                             style: "color: white;" %>
        </span>
        <span class="label label-default">
          <%= link_to "附近餐廳", nearby_path(pid: @place["pid"], 
                                             str: params[:str], 
                                             opt: params[:opt], 
                                             new_str: @place["name"], 
                                             new_opt: "餐廳"), 
                                             style: "color: white;" %>
        </span>
        <span class="label label-default">
          <%= link_to "附近購物", nearby_path(pid: @place["pid"], 
                                             str: params[:str], 
                                             opt: params[:opt], 
                                             new_str: @place["name"], 
                                             new_opt: "購物"), 
                                             style: "color: white;" %>
        </span>    
      </span>       
    </h1>
    <br>

    <% if @place["photos"] %>
      <div class="row" style="padding-left: 20px;">
          <% photo_url_prefix = "https://maps.googleapis.com/maps/api/place/photo?maxheight=400&key=#{ENV["google_api_key"]}&photoreference=" %> 
        <% if @place["photos"][0] %>
          <%= image_tag photo_url_prefix + @place["photos"][0]["photo_ref"], style:"height: 130px; max-width: 200px;" %>
        <% end %>
        <% if @place["photos"][1] %>
          <%= image_tag photo_url_prefix + @place["photos"][1]["photo_ref"], style:"height: 130px; max-width: 200px;" %>
        <% end %>
        <% if @place["photos"][2] %>
          <%= image_tag photo_url_prefix + @place["photos"][2]["photo_ref"], style:"height: 130px; max-width: 200px;" %>
        <% end %>  
        <% if @place["photos"][3] %>
          <%= image_tag photo_url_prefix + @place["photos"][3]["photo_ref"], style:"height: 130px; max-width: 200px;" %>
        <% end %>                  
      </div>
    <% end %>

    <br>

    <h5><b>地址：</b><%= @place["address"] %></h5>

    <h5><b>座標：</b>[<%= @place["lat"] %>, <%= @place["lng"] %>]</h5>

    <h5><b>分類：</b><%= @place["types"] %></h5>

    <% if @place["phone"] %>
      <h5><b>電話：</b><%= @place["phone"] %></h5>
    <% end %>

    <% if @place["website"] %>
      <h5><b>網址：</b><%= link_to @place["website"], @place["website"] %></h5>
    <% end %>

    <% if @place["opening_hours"] %>
      <h5><b>開放時間：</b>
        <% if @place["open_now"] == "false" %>
          <%= link_to "#openhour", :data => {:toggle=>"collapse"} do %>
            今日已休息 <%= @place["opening_hours"][Date.today.wday-1] %>
          <% end %>
        <% else %>
          <%= link_to "#openhour", :data => {:toggle=>"collapse"} do %>
            今日正常營業 <%= @place["opening_hours"][Date.today.wday-1] %>
          <% end %>
        <% end %>   
        <div class="collapse" id="openhour" style="padding-left: 80px;">
          <% @place["opening_hours"].each do |w| %>
            <h5><%= w %><br></h5>
          <% end %>
        </div>  
      </h5>       
    <% end %>

    <br><br>

    <iframe src = <%= @place["google_map_url"] + "&output=embed" %> frameborder='0' style='border:0' width='600' height='300' allowfullscreen></iframe>
    <br><br><br>

    <% if @place["reviews"] %>
      <h4 style="padding-bottom: 10px;">
        <%= link_to @place["user_ratings_total"].to_s + "x 則 Google 評論 ( 2016.May Google API移除顯示 )", @place["url"], target: "_blank" %> 
      </h4>
      <table class="table table-hover table-condensed table-borderless">
        <thead>
          <tr>
            <th width="8%"></th>
            <th width="15%"></th>
            <th width="77%"></th>
          </tr>
        </thead>
        <tbody>
          <% @place["reviews"].each do |r| %>
            <tr>
              <td>
                <% if r["profile_photo_url"] %>
                  <%= image_tag r["profile_photo_url"], height: '40', width: '40', style: "border-radius: 20px;" %>
                <% else %>
                  <%= image_tag "unknow.jpg", height: '40', width: '40', style: "border-radius: 20px;" %>
                <% end %>            
              </td>
              <td>
                <% r["rating"].times do %>
                  <span class="glyphicon glyphicon-star" style="top: 3px"></span>
                <% end %>
                <% (5-r["rating"]).times do %>
                  <span class="glyphicon glyphicon-star-empty" style="top: 3px"></span>
                <% end %>            
              </td>
              <td style="padding-top: 8px;"><%= r["text"] %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>  

app/views/pages/keyword.html.erb
<div class="jumbotron">
  <div class="index-container">
    <h2 style="margin-top: 0">
      <%= link_to "返回首頁", root_path %>  
    </h2>
  </div>
</div>

<div class="index-container">
  <div>
    <!-- Nav tabs -->
    <ul class="nav nav-tabs">
      <li class="active">
        <a href="#google" data-toggle="tab" style="font-size: 1.3em;">Google Place</a>
      </li>
      <% if @places["tripadvisor"] and @places["tripadvisor"].count > 0 %>
        <li >
          <a href="#tripadvisor" data-toggle="tab" style="font-size: 1.3em;">TripAdvisor</a>
        </li>
      <% end %>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
      <div class="tab-pane active" id="google">
        <br><br>
        <div class="well">
          <h3 style="margin: 0"><%= @first_string %>
            搜尋 <%= params[:opt] %> 結果.... ( <%= link_to "隱藏地圖", "#", :id => "click", :onclick => "toggle_visibility('map', 'click');" %> )     
            <% if @places["next_page_token"] %>
              <%= link_to "下一頁", keyword_path(str: @first_string, 
                                                opt: params[:opt], 
                                                token: @places["next_page_token"]), class: "pull-right", style:"font-size: 20px" %>
            <% end %>
          </h3>
        </div> 

        <div>
          <% if @places["results"].count > 0 %>
            <div id="map" style="width: 100%; height: 400px; display: block"></div><br>  
            <%= render "place_list", nearby: false %> 
          <% else %>
            <br>
            <h3>....0筆搜尋結果....</h3>
          <% end %>
        </div>        
      </div>

      <% if @places["tripadvisor"] and @places["tripadvisor"].count > 0 %>
        <div class="tab-pane" id="tripadvisor">
          <%= render "tripadvisor_list" %> 
        </div>
      <% end %>
    </div>
  </div>
  <br><br><br><br>
</div>   


<script type="text/javascript">
  <% if @places  %>
    <% location_array = @places["results"].map {|r| [r["name"], 
                                                    r["lat"], 
                                                    r["lng"], 
                                                    r["rating"] ? r["rating"].to_s : "N/A"]} %>
  
    var locations = <%= raw location_array %>;

    var map = new google.maps.Map(document.getElementById('map'), {
      //zoom: 14,
      //center: new google.maps.LatLng(<%= @auto_complete_lat %>, <%= @auto_complete_lng %>),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });


    var infowindow = new google.maps.InfoWindow();

    var marker, i;
    var bounds = new google.maps.LatLngBounds();

    for (i = 0; i < locations.length; i++) {  
      var bound = new google.maps.LatLng(locations[i][1], locations[i][2]);
      bounds.extend(bound);

      marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        map: map,
        icon: 'http://maps.google.com/mapfiles/ms/icons/green-dot.png'
      });

      google.maps.event.addListener(marker, 'click', (function(marker, i) {
        return function() {
          infowindow.setContent("<h5><b>"+locations[i][0]+"</b></h5>"+"景點評分: "+locations[i][3]);
          infowindow.open(map, marker);
        }
      })(marker, i));
    }
    map.fitBounds(bounds);

    // marker = new google.maps.Marker({
    //   position: new google.maps.LatLng(<%= @auto_complete_lat %>, <%= @auto_complete_lng %>),
    //   map: map,
    //   icon: 'http://maps.google.com/mapfiles/ms/icons/red-dot.png'
    // });

    google.maps.event.addListener(marker, 'click', (function(marker, i) {
      return function() {
        infowindow.setContent("<h5><b>搜尋點" + "</b></h5>");
        infowindow.open(map, marker);
      }
    })(marker, i));    

  <% end %>      
</script>

<script>
  function toggle_visibility(id1, id2) {
     var e1 = document.getElementById(id1);
     if(e1.style.display == 'block')
        e1.style.display = 'none';
     else
        e1.style.display = 'block';

     var e2= document.getElementById(id2);
     if(e2.text == '顯示地圖')
        e2.text = '隱藏地圖';
     else
        e2.text = '顯示地圖';      
  }
</script>

<script >
  $(document).ready(function() {
      <% if params[:token].nil? and params[:button] %>
        <% @split_string.each_with_index do |s, i| %>
          <% if i != 0 %>
            <% path = keyword_url + "?str=" + s + "&opt=" + params[:opt]%>
            window.open("<%= path.html_safe %>", '_blank');
          <% end %>
        <% end %>
      <% end %>
    });

</script>

app/views/pages/nearby.html.erb
<div class="jumbotron">
  <div class="index-container">
    <h2 style="margin-top: 0">
      返回景點 <%= link_to params[:new_str], detail_path(pid: params[:pid], 
                                                        str: params[:str],
                                                        opt: params[:opt]) %>  
    </h2>
  </div>
</div>


<div class="index-container">
  <div class="well">
    <h3 style="margin: 0"><%= params[:new_str] %>
      附近 <%= params[:new_opt] %> 搜尋結果.... ( <%= link_to "隱藏地圖", "#", :id => "click", :onclick => "toggle_visibility('map', 'click');" %> )       
      <% if @places["next_page_token"] %>
        <%= link_to "下一頁", nearby_path(pid: params[:pid], 
                                         new_str: params[:new_str],
                                         new_opt: params[:new_opt],
                                         str: params[:str],
                                         opt: params[:opt],
                                         token: @places["next_page_token"]), class: "pull-right", style:"font-size: 20px" %>
      <% end %>      
    </h3>
  </div> 

  <div id="map" style="width: 100%; height: 400px; display: block"></div><br>  

  <div>
    <%= render "place_list", nearby: true %>      
  </div>
  <br><br><br><br>
</div>   


<script type="text/javascript">
  <% if @places %>
    <% location_array = @places["results"].map {|r| [r["name"], 
                                                    r["lat"], 
                                                    r["lng"], 
                                                    r["rating"] ? r["rating"].to_s : "N/A"]} %>    
  
    var locations = <%= raw location_array %>;

    var map = new google.maps.Map(document.getElementById('map'), {
      //zoom: 14,
      //center: new google.maps.LatLng(<%= @auto_complete_lat %>, <%= @auto_complete_lng %>),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });

    var infowindow = new google.maps.InfoWindow();

    var marker, i;
    var bounds = new google.maps.LatLngBounds();

    for (i = 0; i < locations.length; i++) {  
      var bound = new google.maps.LatLng(locations[i][1], locations[i][2]);
      bounds.extend(bound);

      marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        map: map,
        icon: 'http://maps.google.com/mapfiles/ms/icons/green-dot.png'
      });

      google.maps.event.addListener(marker, 'click', (function(marker, i) {
        return function() {
          infowindow.setContent("<h5><b>"+locations[i][0]+"</b></h5>"+"景點評分: "+locations[i][3]);
          infowindow.open(map, marker);
        }
      })(marker, i));
    }

    map.fitBounds(bounds);

    marker = new google.maps.Marker({
      position: new google.maps.LatLng(<%= @places["auto_complete_lat"] %>, <%= @places["auto_complete_lng"] %>),
      map: map,
      icon: 'http://maps.google.com/mapfiles/ms/icons/red-dot.png'
    });

    google.maps.event.addListener(marker, 'click', (function(marker, i) {
      return function() {
        infowindow.setContent("<h5><b>搜尋點" + "</b></h5>");
        infowindow.open(map, marker);
      }
    })(marker, i));    

  <% end %>      
</script>

<script>
  function toggle_visibility(id1, id2) {
     var e1 = document.getElementById(id1);
     if(e1.style.display == 'block')
        e1.style.display = 'none';
     else
        e1.style.display = 'block';

     var e2= document.getElementById(id2);
     if(e2.text == '顯示地圖')
        e2.text = '隱藏地圖';
     else
        e2.text = '顯示地圖';      
  }
</script>

app/views/pages/statistics.html.erb
<div class="jumbotron">
  <div class="index-container">
    <h2 style="margin-top: 0">統計數據</h2>
    <div class="row">
      <div class="col-xs-9"> 
      </div>  
    </div>  
  </div>
</div>

<div class="index-container">
  <div class="row">
    <div class="col-xs-10">
			<h3>景點統計</h3>
			<br>
			<!-- Nav tabs -->
			<ul class="nav nav-tabs">
				<li class="active">
					<a href="#tab1" data-toggle="tab"><h4>搜尋字串統計</h4></a>
				</li>
				<li >
					<a href="#tab2" data-toggle="tab"><h4>搜尋地點詳情統計</h4></a>
				</li>				
				<li >
					<a href="#tab3" data-toggle="tab"><h4>PID搜尋統計</h4></a>
				</li>
				<li >
					<a href="#tab4" data-toggle="tab"><h4>Web API 執行次數</h4></a>
				</li>				
			</ul>
			
			<!-- Tab panes -->
			<div class="tab-content">
				<div class="tab-pane active" id="tab1">
					<table class="table table-hover table-borderless sortable" id="stat">
						<thead>
							<tr>
								<th width="37%">關鍵字</th>
								<th width="7%">類別</th>
								<th width="7%">次數</th>
								<th width="7%">自動</th>
								<th width="7%"> Debug</th>
								<th width="7%"> 數量</th>
								<th width="7%"> TA</th>
								<th width="21%">最後更新</th>
							</tr>
						</thead>
						<tbody>
							<% @statistics["keyword_count"].each do |k| %>	  
								<tr>
									<td>
										<span class="label label-default" style="font-size: 1.1em">
											<%= link_to k["keyword"].truncate(25), keyword_path(str: k["keyword"], opt: k["option"]), style: "color: white", :target => "_blank" %>
										</span>
									</td>
									<td><%= k["option"] %></td>
									<td><%= k["count"] %></td>
									<td><%= k["autocomplete"] ? "是" : "否" %></td>
									<td><%= k["debug"] %></td>
									<td><%= k["r_count"] %></td>
									<td><%= k["ta_count"] %></td>
									<td><%= Time.parse(k["updated_at"]).in_time_zone('Taipei').strftime("%F %H:%M") %></td>
								</tr>
							<% end %>																																						
						</tbody>
					</table>						
				</div>
				<div class="tab-pane" id="tab2">
					<table class="table table-hover table-borderless" id="stat">
						<thead>
							<tr>
								<th width="65%">名稱</th>
								<th width="10%">次數</th>
								<th width="25%">最後更新</th>
							</tr>
						</thead>
						<tbody>
							<% @statistics["detail_count"].each do |k| %>	  
								<tr>
									<td>
										<span class="label label-default" style="font-size: 1.1em">
											<%= link_to k["name"], detail_path(pid: k["pid"]), style: "color: white", :target => "_blank" %>
										</span>
									</td>
									<td><%= k["count"] %></td>
									<td><%= Time.parse(k["updated_at"]).in_time_zone('Taipei').strftime("%F %H:%M") %></td>
								</tr>
							<% end %>																																						
						</tbody>
					</table>						
				</div>				
				<div class="tab-pane" id="tab3">
					<table class="table table-hover table-borderless" id="stat">
						<thead>
							<tr>
								<th width="55%">PID</th>
								<th width="10%">類別</th>
								<th width="10%">次數</th>
								<th width="25%">最後更新</th>
							</tr>
						</thead>
						<tbody>
							<% @statistics["pid_count"].each do |k| %>	  
								<tr>
									<td>
										<span class="label label-default" style="font-size: 1.1em">
											<%= link_to k["pid"], nearby_path(pid: k["pid"], new_opt: k["option"]), style: "color: white", :target => "_blank" %>
										</span>
									</td>
									<td><%= k["option"] %></td>
									<td><%= k["count"] %></td>
									<td><%= Time.parse(k["updated_at"]).in_time_zone('Taipei').strftime("%F %H:%M") %></td>
								</tr>
							<% end %>																																						
						</tbody>
					</table>						
				</div>
				<div class="tab-pane" id="tab4">
					<table class="table table-hover table-borderless" id="stat">
						<thead>
							<tr>
								<th width="85%">功能</th>
								<th width="15%">次數</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>JSON關鍵字搜尋地點</td>
								<td><%= @statistics["cnt_search_by_keyword"] %></td>
							</tr>
							<tr>
								<td>JSON PID搜尋地點</td>
								<td><%= @statistics["cnt_search_by_pid"] %></td>
							</tr>
							<tr>
								<td>JSON座標搜尋地點</td>
								<td><%= @statistics["cnt_search_by_coordinate"] %></td>
							</tr>
							<tr>
								<td>JSON關鍵字下一頁</td>
								<td><%= @statistics["cnt_get_next_page_keyword"] %></td>
							</tr>
							<tr>
								<td>JSON PID下一頁</td>
								<td><%= @statistics["cnt_get_next_page_pid"] %></td>
							</tr>
							<tr>
								<td>JSON搜尋PID</td>
								<td><%= @statistics["cnt_get_pid"] %></td>
							</tr>
							<tr>
								<td>JSON地點詳情</td>
								<td><%= @statistics["cnt_get_detail"] %></td>
							</tr>																																										
						</tbody>
					</table>						
				</div>				
			</div>
    </div>  
  </div>  
</div>

<br><br><br><br><br>